In [21]:
import pandas as pd 
data=pd.read_csv("Desktop/data.csv")

In [27]:
data.head()

szzs  szzs-1  szzs-2   szzs1   szzs2   gupiao1   gupiao2    gupiao3  \
0  #NAME?     NaN     NaN  3.7527  3.3208 -1.539448 -4.149933  -8.321377   
1  3.7527  #NAME?     NaN  3.3208  0.4867  2.801303  4.189944   6.572770   
2  3.3208  3.7527  #NAME?  0.4867  0.9258  6.337136  5.898123  -2.055800   
3  0.4867  3.3208  3.7527  0.9258  0.2211  1.251490 -1.392405  15.742129   
4  0.9258  0.4867  3.3208  0.2211  3.4977 -0.470865  0.770218   0.000000   

     gupiao4   gupiao5    ...      gupiao291  gupiao292  gupiao293  gupiao294  \
0  -3.402187 -3.727811    ...      -6.849315   2.325581  -5.469679        NaN   
1  10.943396  4.486785    ...       9.243697  -5.113636   6.163522        NaN   
2   9.977324 -9.705882    ...       5.769231   3.992016   4.265403        NaN   
3  -3.195876 -0.651466    ...       1.818182   0.191939  -5.909091        NaN   
4   6.602769  2.360656    ...      -0.178571  -1.532567   7.487923        NaN   

   gupiao295  gupiao296  gupiao297  gupiao298  gupiao299  gupiao300  
0   2.722772        NaN        NaN        NaN        NaN        NaN  
1   1.927711        NaN        NaN        NaN        NaN        NaN  
2   4.964539        NaN        NaN        NaN        NaN        NaN  
3  -0.225225        NaN        NaN        NaN        NaN        NaN  
4   0.677201        NaN        NaN        NaN        NaN        NaN  

[5 rows x 305 columns]

In [39]:
datanew=data.drop([0,1,2])

In [40]:
datanew.dropna(axis=1,inplace=True)

In [43]:
datanew.head()

szzs  szzs-1  szzs-2   szzs1   szzs2   gupiao1   gupiao2    gupiao3  \
3  0.4867  3.3208  3.7527  0.9258  0.2211  1.251490 -1.392405  15.742129   
4  0.9258  0.4867  3.3208  0.2211  3.4977 -0.470865  0.770218   0.000000   
5  0.2211  0.9258  0.4867  3.4977  0.8635 -2.720284 -0.764331   0.000000   
6  3.4977  0.2211  0.9258  0.8635 -0.8628  2.553191  9.242619   0.000000   
7  0.8635  3.4977  0.2211 -0.8628 -1.4235  3.615886  1.410106   0.000000   

    gupiao4   gupiao5    ...      gupiao283  gupiao284  gupiao285  gupiao286  \
3 -3.195876 -0.651466    ...      -1.113586   5.148515  -3.811075   0.204918   
4  6.602769  2.360656    ...      -0.450450   3.013183   7.585506   0.000000   
5  0.299700  5.637412    ...       2.036199   2.010969  -2.895814  -0.408998   
6  3.386454  4.790782    ...       9.312639   3.584229   1.717990   0.205339   
7  3.275530  0.810185    ...       1.419878   0.173010  -0.828553   0.204918   

   gupiao287  gupiao290  gupiao291  gupiao292  gupiao293  gupiao295  
3  -3.065134   0.990099   1.818182   0.191939  -5.909091  -0.225225  
4   4.347826  -0.653595  -0.178571  -1.532567   7.487923   0.677201  
5   2.878788  -0.657895   6.261181   4.474708  -1.123596  -1.121076  
6   2.798233   1.655629   3.198653   0.744879  13.522727   1.814059  
7  -0.358166   0.000000   1.631321   3.327172   2.802803   3.118040  

[5 rows x 262 columns]

In [59]:
X=datanew[["szzs","szzs-1","szzs-2","szzs1","szzs2"]]

In [61]:
X.shape

(253, 5)

In [64]:
Y=datanew.drop(["szzs","szzs-1","szzs-2","szzs1","szzs2"],axis=1)

In [66]:
Y.shape

(253, 257)

In [86]:
test=np.array(Y,dtype=float)

In [87]:
test[0,0]

1.251489869

In [88]:
testx=np.array(X,dtype=float)

In [89]:
X.shape

(253, 5)

In [90]:
testx

array([[ 0.4867,  3.3208,  3.7527,  0.9258,  0.2211],
       [ 0.9258,  0.4867,  3.3208,  0.2211,  3.4977],
       [ 0.2211,  0.9258,  0.4867,  3.4977,  0.8635],
       ..., 
       [-3.3995, -0.3379, -0.5547, -0.4107, -0.2095],
       [-0.4107, -3.3995, -0.3379, -0.2095,  0.    ],
       [-0.2095, -0.4107, -3.3995,  0.    ,  0.    ]])

In [98]:
testx=np.column_stack((np.ones([testx.shape[0],1]),testx))

In [99]:
testx

array([[ 1.    ,  0.4867,  3.3208,  3.7527,  0.9258,  0.2211],
       [ 1.    ,  0.9258,  0.4867,  3.3208,  0.2211,  3.4977],
       [ 1.    ,  0.2211,  0.9258,  0.4867,  3.4977,  0.8635],
       ..., 
       [ 1.    , -3.3995, -0.3379, -0.5547, -0.4107, -0.2095],
       [ 1.    , -0.4107, -3.3995, -0.3379, -0.2095,  0.    ],
       [ 1.    , -0.2095, -0.4107, -3.3995,  0.    ,  0.    ]])

In [100]:
Y=test
X=testx

In [101]:
print(X.shape,Y.shape)

(253, 6) (253, 257)


In [116]:
from numpy import *
beta=np.dot(np.dot(mat(np.dot(X.transpose(),X)).I,X.transpose()),Y)

In [119]:
beta

matrix([[ 0.1402477 ,  0.50852739,  1.12615622, ..., -0.07748273,
         -0.00547352,  0.21630015],
        [ 1.0816859 ,  0.80219923,  0.40296938, ...,  1.02851505,
          1.20339324,  1.12947505],
        [-0.24062651, -0.33680173,  0.22879   , ..., -0.10662138,
         -0.09916978, -0.26126267],
        [ 0.04728311, -0.07288899,  0.09779013, ...,  0.02534147,
          0.06604766, -0.07332731],
        [ 0.05127012,  0.07450616, -0.06580864, ..., -0.11309555,
          0.03730409,  0.05446144],
        [ 0.07685578,  0.03507822,  0.08411766, ..., -0.07153727,
          0.06557888,  0.00849305]])

In [120]:
X.shape

(253, 6)

In [122]:
beta.shape

(6, 257)

In [123]:
Yhat=np.dot(X,beta)

In [130]:
eplison=(Y-Yhat).sum(axis=0)

In [134]:
eplison[0,0]

3.4583447217073626e-14

In [140]:
beta[:,0].shape

(6, 1)

In [143]:
print(X.shape,Y.shape,beta.shape,Yhat.shape)

(253, 6) (253, 257) (6, 257) (253, 257)


In [170]:
np.multiply(Y-Yhat,Y-Yhat).sum(axis=0)

matrix([[   3542.16296313,    5686.78063729,   14284.45396247,
            6514.40176511,    4703.78450008,    4484.25323911,
            2733.80557606,    2193.73087408,    2731.58576136,
            4902.48183517,    9221.40907192,    8334.58197102,
            3176.320197  ,    5495.43772951,   10344.90949566,
            2666.01020744,   10211.98272909,   10014.58597366,
            4244.44585593,    3139.47087664,    6032.07621798,
           11150.25383635,    3918.15793478,    4109.37022797,
            7786.98149142,    4494.95355749,    4414.86496588,
           11490.5531308 ,    3029.01564773,    5866.04930423,
            9325.00957876,    7344.58082936,    5849.61277652,
            4266.6343385 ,    4905.96677026,    5152.37372409,
            5661.79264691,    7187.64623502,    2937.74424597,
            4612.45713174,    3825.77156421,    3333.49779489,
           18564.38348767,    5949.35051077,    9458.33798873,
            3168.24642111,    3867.04926524,    4534.39

In [163]:
Y[0,0]

1.251489869

In [164]:
Yhat[0,0]

0.10952971914167915

In [174]:
beta=pd.DataFrame(beta)

In [178]:
beta.to_csv("Desktop/beta.csv")

In [184]:
eplison=Y-Yhat

In [182]:
eplison=pd.DataFrame(eplison).to_csv("Desktop/eplison.csv")

In [185]:
eplison.shape

(253, 257)